### ISSUE TITLE
Group student submissions before creating chunks

### ISSUE THREAD

**Issue by JaredMiller2022** [jamesjuett/examma-ray#63]
I'm actually not positive that we don't already group submissions before making chunks, but if we don't...

If we make many chunks, there is a much smaller chance of being able to group student submissions within each chunk as compared to against the entire pre-chunked group of submissions, causing us to double grade some unique submissions and missing out on the chance to easily catch potential honor code violations.

**Comment by jamesjuett** [comment]
I think we did this for each (or at least most) of the problems. You can use the script to create 1 big chunk, then group, then use the script again to split it into lots of chunks. (The script preserves groups and grading results when chunking/re-chunking.)
